name: Deploy to Hetzner via SFTP
on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.HETZNER_FTP_USER }}
          server: ${{ secrets.HETZNER_FTP_HOST }}
          port: 2
          local_path: "./"
          remote_path: "/public_html/"
          password: ${{ secrets.HETZNER_FTP_PASS }}
          sftp_only: true
